<a href="https://colab.research.google.com/github/kodi73/Learning-Artificial-Neural-Networks---Forward-Propagation/blob/main/Artificial_Neural_Networks_Forward_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy==1.26.4

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 50.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [1]:
import numpy as np
weights = np.around(np.random.uniform(size = 6), decimals = 2)
biases = np.around(np.random.uniform(size = 3), decimals = 2)

In [2]:
print(weights)
print(biases)

[0.18 0.28 0.76 0.88 0.08 0.16]
[0.32 0.99 0.07]


In [3]:
x1 = 0.5

In [4]:
x2 = 0.85

In [5]:
print('x1 is {} and x2 is {}'.format(x1, x2))

x1 is 0.5 and x2 is 0.85


In [9]:
z11 = x1 * weights[0] + x2 * weights[1] + biases[0]

In [10]:
print('The weighted sum at 1st hidden layer is {}'.format(z11))

The weighted sum at 1st hidden layer is 0.648


In [8]:
z12 = x1 * weights[2] + x2 * weights[3] + biases[1]

In [11]:
print('The weighted sum at 2nd hidden layer is {}'.format(z12))

The weighted sum at 2nd hidden layer is 2.1180000000000003


In [13]:
a11 = 1.0 / (1.0 + np.exp(-z11))
print('The activation of the 1st hidden node is {}'.format(a11))

The activation of the 1st hidden node is 0.6565596258223505


In [14]:
a12 = 1.0 / (1.0 + np.exp(-z12))
print('The activation of the 2nd hidden node is {}'.format(a12))

The activation of the 2nd hidden node is 0.8926404129593664


In [16]:
z2 = a11 * weights[4] + a12 * weights[5] + biases[2]
print('The weighted sum at the output node is {}'.format(z2))

The weighted sum at the output node is 0.2653472361392867


In [19]:
a2 = 1.0 / (1.0 + np.exp(-z2))
print('The output of the network for x1 = 0.5 and x2 = 0.85 is {}'.format(np.around(a2, decimals = 4)))

The output of the network for x1 = 0.5 and x2 = 0.85 is 0.566


This was inefficient. Now we will build a neural network.

In [20]:
n = 2
numHiddenLayers = 2
m = [2, 2]
numOutputNodes = 1

In [21]:
import numpy as np
numPrevNodes = n

network = {}

for layer in range(numHiddenLayers + 1):
  if layer == numHiddenLayers:
    layer_name = "output"
    numNodes = numOutputNodes
  else:
    layer_name = "layer_{}".format(layer + 1)
    numNodes = m[layer]

  network[layer_name] = {}
  for node in range(numNodes):
    node_name = "node_{}".format(node + 1)
    network[layer_name][node_name] = {
        'weights': np.around(np.random.uniform(size = numPrevNodes), decimals = 2),
        'bias': np.around(np.random.uniform(size = 1), decimals = 2)
    }

  numPrevNodes = numNodes

print(network)

{'layer_1': {'node_1': {'weights': array([0.93, 0.99]), 'bias': array([0.24])}, 'node_2': {'weights': array([0.52, 0.95]), 'bias': array([0.3])}}, 'layer_2': {'node_1': {'weights': array([0.47, 0.89]), 'bias': array([0.97])}, 'node_2': {'weights': array([0.57, 0.18]), 'bias': array([0.44])}}, 'output': {'node_1': {'weights': array([0.06, 0.47]), 'bias': array([0.72])}}}


In [24]:
import numpy as np

def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
  num_nodes_prev_layer = num_inputs
  network = {}

  for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
      layer_name = "output"
      num_nodes = num_nodes_output
    else:
      layer_name = "layer_{}".format(layer + 1)
      num_nodes = num_nodes_hidden[layer]

    network[layer_name] = {}
    for node in range(num_nodes):
      node_name = "node_{}".format(node + 1)
      network[layer_name][node_name] = {
          'weights': np.around(np.random.uniform(size = num_nodes_prev_layer), decimals = 2),
          'bias': np.around(np.random.uniform(size = 1), decimals = 2),
      }

    num_nodes_prev_layer = num_nodes

  return network

In [26]:
small_network = initialize_network(5, 3, [3, 2, 3], 1)
print(small_network)

{'layer_1': {'node_1': {'weights': array([0.66, 0.03, 0.75, 0.56, 0.11]), 'bias': array([0.88])}, 'node_2': {'weights': array([0.91, 0.06, 0.31, 0.85, 0.62]), 'bias': array([0.06])}, 'node_3': {'weights': array([0.6 , 0.13, 0.09, 0.44, 0.42]), 'bias': array([0.5])}}, 'layer_2': {'node_1': {'weights': array([0.26, 0.55, 0.86]), 'bias': array([0.19])}, 'node_2': {'weights': array([0.51, 0.61, 0.57]), 'bias': array([0.92])}}, 'layer_3': {'node_1': {'weights': array([0.38, 0.07]), 'bias': array([0.98])}, 'node_2': {'weights': array([0.42, 0.89]), 'bias': array([0.69])}, 'node_3': {'weights': array([0.91, 0.93]), 'bias': array([0.9])}}, 'output': {'node_1': {'weights': array([0.5 , 0.46, 0.62]), 'bias': array([0.6])}}}


In [27]:
def compute_weighted_sum(inputs, weights, bias):
  return np.sum(inputs * weights) + bias

In [29]:
from random import seed
import numpy as np

np.random.seed(12)
inputs = np.around(np.random.uniform(size = 5), decimals = 2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


In [30]:
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']
print(node_weights)
print(node_bias)

weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
print('Weighted sum at 1st hidden layer node is {}'.format(np.around(weighted_sum[0], decimals=4)))

[0.66 0.03 0.75 0.56 0.11]
[0.88]
Weighted sum at 1st hidden layer node is 1.4941


In [31]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

In [32]:
node_output  = node_activation(compute_weighted_sum(inputs, node_weights, node_bias))
print('The output of the first node in the hidden layer is {}'.format(np.around(node_output[0], decimals=4)))

The output of the first node in the hidden layer is 0.8167


In [33]:
def forward_propagate(network, inputs):

    layer_inputs = list(inputs)

    for layer in network:

        layer_data = network[layer]

        layer_outputs = []
        for layer_node in layer_data:

            node_data = layer_data[layer_node]

            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))

        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))

        layer_inputs = layer_outputs

    network_predictions = layer_outputs
    return network_predictions

In [35]:
predictions = forward_propagate(small_network, inputs)
print('The predicted value by the network for the given input is {}'.format(np.around(predictions[0], decimals = 4)))

The outputs of the nodes in hidden layer number 1 is [0.8167, 0.6853, 0.7205]
The outputs of the nodes in hidden layer number 2 is [0.802, 0.8971]
The outputs of the nodes in hidden layer number 3 is [0.7937, 0.8612, 0.9216]
The predicted value by the network for the given input is 0.877


In [36]:
my_network = initialize_network(5, 3, [2, 3, 2], 3)

In [37]:
inputs = np.around(np.random.uniform(size=5), decimals=2)

In [38]:
predictions = forward_propagate(my_network, inputs)
print('The predicted values by the network for the given input are {}'.format(predictions))

The outputs of the nodes in hidden layer number 1 is [0.8857, 0.8889]
The outputs of the nodes in hidden layer number 2 is [0.7822, 0.6965, 0.7411]
The outputs of the nodes in hidden layer number 3 is [0.868, 0.881]
The predicted values by the network for the given input are [0.8952, 0.8222, 0.8035]
